apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert
  namespace: demo
spec:
  secretName: demo
  issuerRef:
    name: kubeissuer
    kind: ClusterIssuer
  dnsNames:
  - gke.ioinfo.shop 