# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: kubeissuer
#   namespace: demo
# spec:
#   acme:
#     server: https://acme-staging-v02.api.letsencrypt.org/directory
#     email: vamsi.krishna@tensure.io
#     privateKeySecretRef:
#       name: kubeissuer
#     solvers:
#     - http01:
#         ingress:
#           class: gce

# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: vktest@test.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          name: nginx-ingress