replicaCount: 2

image:
  repository: vamckrish08/kubernetes
  tag: "1"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: gce
  host: new-helm.ioinfo.shop
  externaldnshostname: new-helm.ioinfo.shop

tls:
  enabled: true
  secretName: new-helm-prod-secret

certManager:
  email: vamsi.krishna@tensure.io
  clusterIssuerName: new-helm-letsencrypt-issuer

project:
  projectName: vamsi-krishna-sandbox

deployment:
  enabled: false
