apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prune-application
  namespace: argocd
spec:
  destination:
    namespace: automated-sync
    server: https://kubernetes.default.svc
  project: default
  source:
    path: prod-cluster/argocd/directoryofmanifests
    repoURL: https://github.com/VamsiKrishna082/gitops-bridge-automation
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
    