apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: argocdToken
      remoteRef:
        key: argocd_token
  target:
    template:
      engineVersion: v2
      data:
        token: "{{.argocdToken}}"
        