apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: backstageClientSecret
      remoteRef:
        key: vamsi-krishna-sandbox-oauth-client-secret
  target:
    template:
      engineVersion: v2
      data:
        secret: "{{.backstageClientSecret}}"