apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-github-integration-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: backstageGithubKey
      remoteRef:
        key: vamsi-krishna-sandbox-backstage-github-key
  target:
    template:
      engineVersion: v2
      data:
        password: "{{.backstageGithubKey}}"
        