apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-host-name
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: backstageHostName
      remoteRef:
        key: backstage_host_name
  target:
    template:
      engineVersion: v2
      data:
        hostname: "{{.backstageHostName}}"
        