apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-cloudsql-ip
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: backstageDbcloudsqlip
      remoteRef:
        key: vamsi-krishna-sandbox-cloud-sql-ip
  target:
    template:
      engineVersion: v2
      data:
        ip: "{{.backstageDbcloudsqlip}}"