apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: backstageDbPassword
      remoteRef:
        key: vamsi-krishna-sandbox-backstage-db-password
  target:
    template:
      engineVersion: v2
      data:
        password: "{{.backstageDbPassword}}"