apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: githubAppClientSecret
      remoteRef:
        key: github_app_client_secret
  target:
    template:
      engineVersion: v2
      data:
        secret: "{{.githubAppClientSecret}}"
        