apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  data:
    - secretKey: githubClientSecret
      remoteRef:
        key: github_client_secret
  target:
    template:
      engineVersion: v2
      data:
        secret: "{{.githubClientSecret}}"
        