apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage-db-password.yaml
  - backstage-db-cloudsql-ip.yaml
  - backstage-backend-secrets.yaml
  - backstage-github-key.yaml
  - backstage-client-id.yaml
  - backstage-client-secret.yaml
  - argocd-host-name.yaml
  - argocd-token.yaml
  - backstage-host-name.yaml
  - github-client-id.yaml
  - github-client-secret.yaml
  - grafana-host-name.yaml
  - grafana-token.yaml
  - techdocs-gcs-bucket.yaml
  - github-app-client-id.yaml
  - github-app-client-secret.yaml
  - github-app-id.yaml
  - github-app-private-key.yaml
  - github-app-webhook-secret.yaml
  