apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backstage-db-password.yaml
  # - backstage-db-cloudsql-ip.yaml
  # - backstage-backend-secrets.yaml
  # - backstage-github-key.yaml
  # - backstage-client-id.yaml
  # - backstage-client-secret.yaml