cert:
  email: vamsi.krishna@tensure.io
  gcpProject: vamsi-krishna-sandbox

secrets:
  db:
    name: backstage-db-password
    key: password
  sql:
    name: backstage-db-cloudsql-ip
    key: ip
  loginid:
    name: backstage-client-id
    key: id
  loginsecret:
    name: backstage-client-secret
    key: secret
  backendauth:
    name: backstage-backend-auth
    key: password
  github:
    name: backstage-github-integration-key
    key: password
  backstage_host:
    name: backstage-host-name
    key: hostname
  github_client_id:
    name: github-client-id
    key: id
  github_client_secret:
    name: github-client-secret
    key: secret
  grafana_host:
    name: grafana-host-name
    key: hostname
  grafana_token:
    name: grafana-token
    key: token
  techdocs_gcs_bucket:
    name: techdocs-gcs-bucket
    key: name
  argocd_host:
    name: argocd-host-name
    key: hostname
  argocd_token:
    name: argocd-token
    key: token

ingress:
  host: backstage-new.ioinfo.shop
  enabled: true
  class: gce
  allowHttp: "true"
