apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
  namespace: prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuerName }}
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.project.projectName }}
