apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: prod
spec:
  selector:
    app: {{ .Release.Name }}-backend2
    tier: backend2
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
