apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-cainjector-leases
  namespace: cert-manager-leader
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-cainjector-leases-binding
  namespace: cert-manager-leader
subjects:
  - kind: ServiceAccount
    name: cert-manager-cainjector
    namespace: cert-manager
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-cainjector-leases
  apiGroup: rbac.authorization.k8s.io