apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: new-helm-prod-secret
      namespace: prod
      jsonPointers:
        - /data
  source: 
    helm:
      releaseName: first-app-version1
    path: prod-cluster/helm/app
    repoURL: https://github.com/VamsiKrishna082/gitops-bridge-automation
    targetRevision: main