apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: custom-project-1
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  # - '!https://github.com/devopshobbies/argocd-tutorial.git' ## Use '!' to place repo in BlackList, if we remove '!' the repo will be placed in WhiteList
  - '*' ## '*' means we are allowed to use any repos
  roles:
    - name: read-sync
      description: "this role can be used for reading applications"
      policies:
        - p, proj:project-role:read-sync, applications, get, project-role/*, allow
        # - p, proj:project-role:read-sync, applications, sync, project-role/*, allow