apiVersion: v1
kind: Secret
metadata:
  name: credential-template-secret
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repo-creds #label is important
stringData:
  type: git
  url: https://github.com/VamsiKrishna082/
  username: argo
  password: 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